[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DashCoreComponents = "1b08a953-4be3-4667-9a23-9da06441d987"
DashHtmlComponents = "1b08a953-4be3-4667-9a23-24100242a84a"
DashTable = "1b08a953-4be3-4667-9a23-f0e2ba4deb9a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
